#!/bin/bash

SRC_DIR="src"
INC_DIR="include"
BIN_DIR="bin"
OUTPUT="$BIN_DIR/main"

mkdir -p $BIN_DIR

gcc -Wall -Wextra main.c $SRC_DIR/*.c -I$INC_DIR -pthread -o $OUTPUT

if [ $? -eq 0 ]; then
    ./$OUTPUT
fi